######################## default configuration ####################
#
baseURL = "https://zolinaturals.github.io/zoli_website/"
title = "ZOLI website"
theme = "hargo-hugo"

[frontmatter]
format = "yaml"

# Default time zone for time stamps; use any valid tz database name:
#   https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
timeZone = "Europe/Ljubljana"
# post pagination
# see https://gohugo.io/extras/pagination/
pagination.pagerSize = 10
# post excerpt
# see https://gohugo.io/content-management/excerpts/
summaryLength = 20
# google analytics
# example: UA-123456-78, for more info,
# read the article https://support.google.com/analytics/answer/1008080?hl=en
googleAnalytics = "UA-123456-78"
# disqus short name
# we use disqus to show comments in blog posts.
# To install disqus please follow this tutorial:
#  https://portfolio.peter-baumgartner.net/2017/09/10/how-to-install-disqus-on-hugo/
disqusShortname = "themefisher-template"
timeout = "500s"

######################### Language related settings ########################
# Default language settings. If languageCode is missing Hugo had issues.
languageCode = "sl"
DefaultContentLanguage = "sl"
defaultContentLanguageInSubdir = false

# Not optional. If you have more than one language, you must configure them under the
# [languages] section. Enables multilingual mode in Hugo.
[languages]
[languages.sl]
languageName = "Slovenščina"
languageCode = "sl"
weight = 1

[languages.en]
languageName = "English"
languageCode = "en"
weight = 2

# Disable language.
# example: ["fr"] for disable french language.
# see https://gohugo.io/content-management/multilingual/
disableLanguages = []
#  If hasCJKLanguage true, auto-detect Chinese/Japanese/Korean Languages in the content.
# see: https://gohugo.io/getting-started/configuration/#hascjklanguage
hasCJKLanguage = false

############################# Build ##############################
[build]
noJSConfigInAssets = false
useResourceCacheWhen = 'fallback'
[build.buildStats]
enable = true
[[build.cachebusters]]
source = 'assets/.*\.(js|ts|jsx|tsx)'
target = '(js|scripts|javascript)'
[[build.cachebusters]]
source = 'assets/.*\.(css|sass|scss)$'
target = '(css|styles|scss|sass)'
[[build.cachebusters]]
source = 'assets/.*\.(.*)$'
target = '$1'

############################# Outputs ##############################
[outputs]
home = ["HTML", "RSS"]

############################# Imaging ##############################
[imaging]
# See https://github.com/disintegration/imaging
# Default JPEG or WebP quality setting. Default is 75.
quality = 90
resampleFilter = "lanczos"


############################# Caches ###############################
[caches]
[caches.images]
dir = ":resourceDir/_gen"
maxAge = "720h"

[caches.assets]
dir = ":resourceDir/_gen"
maxAge = "720h"

############################# Markup ###############################
[markup]
[markup.goldmark.renderer]
unsafe = true

############################# Plugins ##############################
[params.plugins]

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"


#################### default parameters ################################
[params]
logo = "images/logo.png"
home = "Domov"
# Meta data
description = "This is Luka's meta description"
author = "Luka & Themefisher"
# google map
gmapAPI = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
mapLatitude = "46.1639179074423"
mapLongitude = "14.701269559794016"
mapMarker = "images/marker.png"
# Google Analitycs
googleAnalyticsID = "" # Your ID
# Contact Information
mobile = "+386 40 990 705"
email = "barbi.jeras@gmail.com"
location = "Gradišče pri Lukovici 5b, 1225 Lukovica"
# copyright
# copyright = "| Copyright &copy; 2019 [Gethugothemes](https://gethugothemes.com) All Rights Reserved |"
copyright = "| Copyright &copy; 2025 Barbi All Rights Reserved |"
# Snipcart Credentials
# TODO (lj): Initially remove snipcart functionality. Later we can add.
snipcartApiKey = "M2E5YjA3NjMtYzRiYS00YzVjLWEyYWYtNDY5ZDI0OWZhYjg5"
currencySymbol = "€"
#"$"

# Preloader
[params.preloader]
enable = true
preloader = "" # use .png , .svg or .gif format

# Product Rating
# it works with https://rating-widget.com/ , you will get the ID and publicKey after creating your account there.
[params.rating]
enable = true
websiteID = "444334"
publicKey = "811cf0927332bf51f2e12f84608594ac"

# Social Site
[[params.social]]
icon = "ti-facebook"
link = "#"

[[params.social]]
icon = "ti-twitter-alt"
link = "#"

[[params.social]]
icon = "ti-youtube"
link = "#"

[[params.social]]
icon = "ti-instagram"
link = "#"

[[params.social]]
icon = "ti-pinterest"
link = "#"

# Contact Form
# TODO (lj): Figure out how this works.
[params.contact]
formAction = "#" # contact form works with formspree.io
